export default function Head() {
  return (
    <>
      <title>
        Electronic Blue Friends - A simple, practical, and beautiful web
        application for menstrual period records
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/_assets/favicon.ico" />
    </>
  );
}
